---

- hosts: docker
  become: true
  tasks:

  - name: Add Docker keyring
    ansible.builtin.get_url: 
      url: https://download.docker.com/linux/ubuntu/gpg
      dest: /etc/apt/keyrings/docker.asc
      mode : "a+r"
  - name: Add Docker repro
    ansible.builtin.apt_repository:
     repo: deb [arch=amd64 signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu jammy stable
     state: present
     filename: docker
     update_cache: true
  - name: Docker installation
    ansible.builtin.apt:
      name:
       - docker-ce
       - docker-ce-cli
       - docker-buildx-plugin
       - docker-compose-plugin
       - containerd.io
      state: present
  

